name: Build Web App

on:
  push:
    branches: [ flashram-fix ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm start:config   # ou o comando que você encontrou

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ootmm-webapp
          path: build/     # ou a pasta de saída (pode ser "build", "out", etc.)
